---
# tasks file for user
- name: reading csv file
  become: no
  read_csv:
    path: "{{ filepath }}"
  register: userlist
  delegate_to: localhost
- name: display userlist
  debug:
    var: userlist.list
- name: add users
  user:
    name: "{{item.username}}"
    groups: sudo
    shell: /bin/bash    
    password: "{{ lookup('password', 'storage/credentials/' + item.username + '.txt encrypt=sha512_crypt length=12') }}"
    createhome: yes
  loop: "{{userlist.list}}"
