---
- name: display sudoers
  debug:
    msg: "username: {{ item.username }}, groups: {{item.groups | default('-')}}"  
  loop: "{{sudoers}}"
  loop_control:
    index_var: idx
    label:
      - "user {{idx+1}}"
- name: add users
  user:
    name: "{{item.username}}"
    groups: "{{ item.groups | default('sudo') }}"
    shell: /bin/bash
    password: "{{ item.password | password_hash('sha512', 'hhuBH3KM24WTqYzk') }}"
    createhome: yes
  loop: "{{sudoers}}"
  loop_control:
    label:
      - "{{item.username}}"
