---
- name: display sudoers
  debug:
    var: sudoers
- name: add users
  user:
    name: "{{item.username}}"
    groups: "{{ item.groups | default('sudo') }}"
    shell: /bin/bash    
    password: "{{ lookup('password', 'storage/credentials/' + item.username + '.txt encrypt=sha512_crypt length=12') }}"
    createhome: yes
  loop: "{{sudoers}}"
- pause:
    minutes: 5
